// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fprazmjkekhiyusqifwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwcmF6bWprZWtoaXl1c3FpZndqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NzQ2NjgsImV4cCI6MjA1OTE1MDY2OH0.31gAcOZxTxay-T6BtR6gL3Sv1ccQ3A66VNnlDuj-AS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);